### ISSUE TITLE
.mabe files can't read negative numbers outside quotes

### ISSUE THREAD

**Issue by alackles** [mercere99/MABE2#10]
Right now, `.mabe`  files don't seem to be able to read negative numbers unless they're in quotation marks, which is a confusing convention. it also means the `.gen` file sometimes generates a random seed that the `.mabe` file can't read, and that setting a min value on a ValsOrg less than 0 needs quotation marks even though the max value does not.

**Comment by mercere99** [comment]
This was a problem in the parser - now fixed!
